#!/bin/bash
set -euo pipefail

cols="$(tput cols 2>/dev/null)"
cols=$((cols - 5))

msg=
value=
if [[ -f "${zquickinit_config}/etc/network/configure" ]]; then
	IFS= read -rd '' value <"${zquickinit_config}/etc/network/configure" || :
else
	msg="(Autogenerated default example configuration to configure interfaces statically)"
	IFS= read -rd '' value <<-EOF || :
		# Set up static IP addresses for interfaces
		# ip link set dev eth0 up
		# ip addr add 192.168.1.2/24 brd + dev eth0
		# ip route add default via 192.168.1.1
	EOF
fi
echo
gum format "Edit network script. Any interfaces without an IP with have DHCP enabled. ${msg}" "See https://docs.voidlinux.org/config/network/index.html" "" "Empty string will leave unconfigured."
echo
out=$(gum write --char-limit=0 --height=10 --width="$cols" --placeholder="network" --value="${value}")
if [[ -n $out ]]; then
	mkdir -p "${zquickinit_config}/etc/network"
	echo "$out" >"${zquickinit_config}/etc/network/configure"
else
	gum format "No network configuration. DHCP will be enabled on all interfaces."
fi
