xbps-packages:
 - gptfdisk
 - parted
 - util-linux
 - efibootmgr
 - dosfstools
 - mtools
 - kpartx
 - nvme-cli
help: "Includes useful commands for creating and viewing partitions and filesystems. Also `efibootmgr`, `cryptsetup`.  "